### ISSUE TITLE
Old voteorders cannot be executed at once, because of "STEEM_MIN_VOTE_INTERVAL_SEC: Can only vote once every 3 seconds."

### ISSUE THREAD

**Issue by noisy** [noisy-witness/steem-wise-cli#1]
```
Synchronization: Loading rulesets since last synchronized voteorder
Synchronization: Loading new voteorders from voters you delegated to
Synchronization: Loading voteorders from jblew...
Synchronization: Loading voteorders from nicniezgrublem...
Synchronization: Done loading voteorders from jblew.
Synchronization: Done loading voteorders from nicniezgrublem.
Synchronization: Loaded all voteorders, validating...
Synchronization: Starting validation of @nicniezgrublem: /@annanowicka/wierzenia-i-obrzadek-pogrzebowy-w-epoce-brazu-i-wczesnej-epoce-zelaza-na-terenie-polski-cz-3-2-obrzadek-pogrzebowy-w-epoce-brazu
Synchronization: Starting validation of @nicniezgrublem: /@romualdd/matematyka-sredniowiecza-a-scholastyka-czasow-nowozytnych
Synchronization: Starting validation of @nicniezgrublem: /@jasiu/re-lokibalboa-re-jasiu-re-glodniwiedzy-the-boring-company-ukonczylo-budowe-pierwszego-tunelu-pod-los-angeles-20180511t230007328z
Synchronization: Validation  succeeded for voteorder of @nicniezgrublem: /@jasiu/re-lokibalboa-re-jasiu-re-glodniwiedzy-the-boring-company-ukonczylo-budowe-pierwszego-tunelu-pod-los-angeles-20180511t230007328z
Synchronization: Validation  succeeded for voteorder of @nicniezgrublem: /@annanowicka/wierzenia-i-obrzadek-pogrzebowy-w-epoce-brazu-i-wczesnej-epoce-zelaza-na-terenie-polski-cz-3-2-obrzadek-pogrzebowy-w-epoce-brazu
Synchronization: Validation  succeeded for voteorder of @nicniezgrublem: /@romualdd/matematyka-sredniowiecza-a-scholastyka-czasow-nowozytnych
[
  [
    "vote",
    { 
      "voter": "noisy",
      "author": "annanowicka",
      "permlink": "wierzenia-i-obrzadek-pogrzebowy-w-epoce-brazu-i-wczesnej-epoce-zelaza-na-terenie-polski-cz-3-2-obrzadek-pogrzebowy-w-epoce-brazu",
      "weight": 6000
    }
  ],
  [
    "vote",
    { 
      "voter": "noisy",
      "author": "romualdd",
      "permlink": "matematyka-sredniowiecza-a-scholastyka-czasow-nowozytnych",
      "weight": 2000
    }
  ],
  [
    "vote",
    { 
      "voter": "noisy",
      "author": "jasiu",
      "permlink": "re-lokibalboa-re-jasiu-re-glodniwiedzy-the-boring-company-ukonczylo-budowe-pierwszego-tunelu-pod-los-angeles-20180511t230007328z",
      "weight": 50
    }
  ],
  [
    "custom_json",
    { 
      "required_auths": [],
      "required_posting_auths": [
        "noisy"
      ],
      "id": "smartvote",
      "json": "{\"name\":\"confirm_votes\",\"voteorders\":[{\"transaction_id\":\"6078c1cec5f16c2234d378448b63eeb22c34724a\",\"operation_num\":0,\"invalid\":false},{\"transaction_id\":\"ac37bee632b65a717a40b05ee96e8f6bbf69288e\",\"operation_num\":0,\"invalid\":false},{\"transaction_id\":\"5f8671cf57942706cd9fd65fde763772b1e19b43\",\"operation_num\":0,\"invalid\":false}]}"
    }
  ]
]
Synchronization: Sending votes...

{ RPCError: Assert Exception:elapsed_seconds >= STEEM_MIN_VOTE_INTERVAL_SEC: Can only vote once every 3 seconds.
    at new RPCError (/home/deploy/smarvotes/cli/node_modules/steem/lib/api/transports/http.js:39:106)
    at /home/deploy/smarvotes/cli/node_modules/steem/lib/api/transports/http.js:74:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  cause: 
   { RPCError: Assert Exception:elapsed_seconds >= STEEM_MIN_VOTE_INTERVAL_SEC: Can only vote once every 3 seconds.
    at new RPCError (/home/deploy/smarvotes/cli/node_modules/steem/lib/api/transports/http.js:39:106)
    at /home/deploy/smarvotes/cli/node_modules/steem/lib/api/transports/http.js:74:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
     name: 'RPCError',
     code: -32000,
     data: 
      { code: 10,
        name: 'assert_exception',
        message: 'Assert Exception',
        stack: [Array] } },
  isOperational: true,
  code: -32000,
  data: 
   { code: 10,
     name: 'assert_exception',
     message: 'Assert Exception',
     stack: [ [Object], [Object], [Object], [Object], [Object] ] } }
```

**Comment by Jblew** [comment]
This issue is now solved in version 0.4.0+ (which uses steem-wise-core lib v0.17.2). The sync-votes command is removed, and votes are synced using daemon mode. In the daemon mode one voteorder is synced per one block.
