### ISSUE TITLE
"Error: HTTP 504: Gateway Time-out" during sync-rules

### ISSUE THREAD

**Issue by noisy** [noisy-witness/steem-wise-cli#11]
```
$ wise -c config.json sync-rules rules.json 
Error: HTTP 504: Gateway Time-out
    at /usr/local/lib/node_modules/steem-wise-cli/node_modules/steem/lib/api/transports/http.js:66:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by Jblew** [comment]
Fallback Api will be introduced together with WisePlatform.

**Comment by noisy** [comment]
![selection_980](https://user-images.githubusercontent.com/201263/43545144-5a1e8f0c-95d5-11e8-9a7b-2f76ccb02498.png)

We cannot wait for WisePlatform. This is unusable with that bug

**Comment by noisy** [comment]
@Jblew do you think this is still an issue?

We do not have `sync-rules` anymore, and also... I didn't encounter this issue during last testing of upload/download-rules

What special condition might be needed to reproduce this error?

**Comment by Jblew** [comment]
Solution: add retry in upload-rules command
